const USER_LOGIN = "USER_LOGIN";
const USER_LOGOUT = "USER_LOGOUT";
const EVENT_TYPE = "EVENT_TYPE";
const SAVE_EVENT = "SAVE_EVENT";
const USER_SIGN_UP = "USER_SIGN_UP";
const EVENT_TYPE_BY_ID = "EVENT_TYPE_BY_ID";
const RESET_PASSWORD = "RESET_PASSWORD";

const Types = {
  EVENT_TYPE,
  USER_LOGIN,
  USER_LOGOUT,
  SAVE_EVENT,
  USER_SIGN_UP,
  EVENT_TYPE_BY_ID,
  RESET_PASSWORD
}

export default Types